// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ynx/ynx/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SystemConfig struct {
	// enabled controls whether the chain deploys the system contracts during InitGenesis.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// deployer_address is the EVM deployer address used for deterministic deployments.
	// It MAY be provided as 0x... (hex) or a chain bech32 address.
	DeployerAddress string `protobuf:"bytes,2,opt,name=deployer_address,json=deployerAddress,proto3" json:"deployer_address,omitempty"`
	// team_beneficiary_address receives the vested team allocation in the NYXTTeamVesting contract.
	// It MAY be provided as 0x... (hex) or a chain bech32 address.
	TeamBeneficiaryAddress string `protobuf:"bytes,3,opt,name=team_beneficiary_address,json=teamBeneficiaryAddress,proto3" json:"team_beneficiary_address,omitempty"`
	// community_recipient_address receives the community allocation.
	// It MAY be provided as 0x... (hex) or a chain bech32 address.
	CommunityRecipientAddress string `protobuf:"bytes,4,opt,name=community_recipient_address,json=communityRecipientAddress,proto3" json:"community_recipient_address,omitempty"`
	// genesis_supply is the NYXT ERC20 genesis supply (uint256) as a base-10 string.
	GenesisSupply string `protobuf:"bytes,5,opt,name=genesis_supply,json=genesisSupply,proto3" json:"genesis_supply,omitempty"`
	// Allocation percentages (must sum to 100).
	TeamPercent      uint32 `protobuf:"varint,6,opt,name=team_percent,json=teamPercent,proto3" json:"team_percent,omitempty"`
	TreasuryPercent  uint32 `protobuf:"varint,7,opt,name=treasury_percent,json=treasuryPercent,proto3" json:"treasury_percent,omitempty"`
	CommunityPercent uint32 `protobuf:"varint,8,opt,name=community_percent,json=communityPercent,proto3" json:"community_percent,omitempty"`
	// Governance params.
	VotingDelayBlocks    uint64 `protobuf:"varint,9,opt,name=voting_delay_blocks,json=votingDelayBlocks,proto3" json:"voting_delay_blocks,omitempty"`
	VotingPeriodBlocks   uint64 `protobuf:"varint,10,opt,name=voting_period_blocks,json=votingPeriodBlocks,proto3" json:"voting_period_blocks,omitempty"`
	ProposalThreshold    string `protobuf:"bytes,11,opt,name=proposal_threshold,json=proposalThreshold,proto3" json:"proposal_threshold,omitempty"`
	ProposalDeposit      string `protobuf:"bytes,12,opt,name=proposal_deposit,json=proposalDeposit,proto3" json:"proposal_deposit,omitempty"`
	QuorumPercent        uint64 `protobuf:"varint,13,opt,name=quorum_percent,json=quorumPercent,proto3" json:"quorum_percent,omitempty"`
	TimelockDelaySeconds uint64 `protobuf:"varint,14,opt,name=timelock_delay_seconds,json=timelockDelaySeconds,proto3" json:"timelock_delay_seconds,omitempty"`
	// Vesting params.
	VestingCliffSeconds    uint64   `protobuf:"varint,15,opt,name=vesting_cliff_seconds,json=vestingCliffSeconds,proto3" json:"vesting_cliff_seconds,omitempty"`
	VestingDurationSeconds uint64   `protobuf:"varint,16,opt,name=vesting_duration_seconds,json=vestingDurationSeconds,proto3" json:"vesting_duration_seconds,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *SystemConfig) Reset()         { *m = SystemConfig{} }
func (m *SystemConfig) String() string { return proto.CompactTextString(m) }
func (*SystemConfig) ProtoMessage()    {}
func (*SystemConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfacd17f76421fa4, []int{0}
}
func (m *SystemConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemConfig.Unmarshal(m, b)
}
func (m *SystemConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemConfig.Marshal(b, m, deterministic)
}
func (m *SystemConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemConfig.Merge(m, src)
}
func (m *SystemConfig) XXX_Size() int {
	return xxx_messageInfo_SystemConfig.Size(m)
}
func (m *SystemConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SystemConfig proto.InternalMessageInfo

func (m *SystemConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *SystemConfig) GetDeployerAddress() string {
	if m != nil {
		return m.DeployerAddress
	}
	return ""
}

func (m *SystemConfig) GetTeamBeneficiaryAddress() string {
	if m != nil {
		return m.TeamBeneficiaryAddress
	}
	return ""
}

func (m *SystemConfig) GetCommunityRecipientAddress() string {
	if m != nil {
		return m.CommunityRecipientAddress
	}
	return ""
}

func (m *SystemConfig) GetGenesisSupply() string {
	if m != nil {
		return m.GenesisSupply
	}
	return ""
}

func (m *SystemConfig) GetTeamPercent() uint32 {
	if m != nil {
		return m.TeamPercent
	}
	return 0
}

func (m *SystemConfig) GetTreasuryPercent() uint32 {
	if m != nil {
		return m.TreasuryPercent
	}
	return 0
}

func (m *SystemConfig) GetCommunityPercent() uint32 {
	if m != nil {
		return m.CommunityPercent
	}
	return 0
}

func (m *SystemConfig) GetVotingDelayBlocks() uint64 {
	if m != nil {
		return m.VotingDelayBlocks
	}
	return 0
}

func (m *SystemConfig) GetVotingPeriodBlocks() uint64 {
	if m != nil {
		return m.VotingPeriodBlocks
	}
	return 0
}

func (m *SystemConfig) GetProposalThreshold() string {
	if m != nil {
		return m.ProposalThreshold
	}
	return ""
}

func (m *SystemConfig) GetProposalDeposit() string {
	if m != nil {
		return m.ProposalDeposit
	}
	return ""
}

func (m *SystemConfig) GetQuorumPercent() uint64 {
	if m != nil {
		return m.QuorumPercent
	}
	return 0
}

func (m *SystemConfig) GetTimelockDelaySeconds() uint64 {
	if m != nil {
		return m.TimelockDelaySeconds
	}
	return 0
}

func (m *SystemConfig) GetVestingCliffSeconds() uint64 {
	if m != nil {
		return m.VestingCliffSeconds
	}
	return 0
}

func (m *SystemConfig) GetVestingDurationSeconds() uint64 {
	if m != nil {
		return m.VestingDurationSeconds
	}
	return 0
}

type SystemContracts struct {
	Nyxt                 string   `protobuf:"bytes,1,opt,name=nyxt,proto3" json:"nyxt,omitempty"`
	Timelock             string   `protobuf:"bytes,2,opt,name=timelock,proto3" json:"timelock,omitempty"`
	Treasury             string   `protobuf:"bytes,3,opt,name=treasury,proto3" json:"treasury,omitempty"`
	Governor             string   `protobuf:"bytes,4,opt,name=governor,proto3" json:"governor,omitempty"`
	TeamVesting          string   `protobuf:"bytes,5,opt,name=team_vesting,json=teamVesting,proto3" json:"team_vesting,omitempty"`
	OrgRegistry          string   `protobuf:"bytes,6,opt,name=org_registry,json=orgRegistry,proto3" json:"org_registry,omitempty"`
	SubjectRegistry      string   `protobuf:"bytes,7,opt,name=subject_registry,json=subjectRegistry,proto3" json:"subject_registry,omitempty"`
	Arbitration          string   `protobuf:"bytes,8,opt,name=arbitration,proto3" json:"arbitration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemContracts) Reset()         { *m = SystemContracts{} }
func (m *SystemContracts) String() string { return proto.CompactTextString(m) }
func (*SystemContracts) ProtoMessage()    {}
func (*SystemContracts) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfacd17f76421fa4, []int{1}
}
func (m *SystemContracts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemContracts.Unmarshal(m, b)
}
func (m *SystemContracts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemContracts.Marshal(b, m, deterministic)
}
func (m *SystemContracts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemContracts.Merge(m, src)
}
func (m *SystemContracts) XXX_Size() int {
	return xxx_messageInfo_SystemContracts.Size(m)
}
func (m *SystemContracts) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemContracts.DiscardUnknown(m)
}

var xxx_messageInfo_SystemContracts proto.InternalMessageInfo

func (m *SystemContracts) GetNyxt() string {
	if m != nil {
		return m.Nyxt
	}
	return ""
}

func (m *SystemContracts) GetTimelock() string {
	if m != nil {
		return m.Timelock
	}
	return ""
}

func (m *SystemContracts) GetTreasury() string {
	if m != nil {
		return m.Treasury
	}
	return ""
}

func (m *SystemContracts) GetGovernor() string {
	if m != nil {
		return m.Governor
	}
	return ""
}

func (m *SystemContracts) GetTeamVesting() string {
	if m != nil {
		return m.TeamVesting
	}
	return ""
}

func (m *SystemContracts) GetOrgRegistry() string {
	if m != nil {
		return m.OrgRegistry
	}
	return ""
}

func (m *SystemContracts) GetSubjectRegistry() string {
	if m != nil {
		return m.SubjectRegistry
	}
	return ""
}

func (m *SystemContracts) GetArbitration() string {
	if m != nil {
		return m.Arbitration
	}
	return ""
}

type GenesisState struct {
	Params               Params          `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	System               SystemConfig    `protobuf:"bytes,2,opt,name=system,proto3" json:"system"`
	SystemContracts      SystemContracts `protobuf:"bytes,3,opt,name=system_contracts,json=systemContracts,proto3" json:"system_contracts"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfacd17f76421fa4, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetSystem() SystemConfig {
	if m != nil {
		return m.System
	}
	return SystemConfig{}
}

func (m *GenesisState) GetSystemContracts() SystemContracts {
	if m != nil {
		return m.SystemContracts
	}
	return SystemContracts{}
}

func init() {
	proto.RegisterType((*SystemConfig)(nil), "ynx.ynx.v1.SystemConfig")
	proto.RegisterType((*SystemContracts)(nil), "ynx.ynx.v1.SystemContracts")
	proto.RegisterType((*GenesisState)(nil), "ynx.ynx.v1.GenesisState")
}

func init() { proto.RegisterFile("ynx/ynx/v1/genesis.proto", fileDescriptor_dfacd17f76421fa4) }

var fileDescriptor_dfacd17f76421fa4 = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0x36, 0x35, 0x4d, 0x9b, 0x49, 0xd2, 0xa4, 0xd3, 0x5a, 0xd7, 0xf6, 0xc2, 0x58, 0x10, 0x22,
	0x6a, 0xd2, 0x46, 0x91, 0x5e, 0x09, 0xfd, 0x01, 0x41, 0x44, 0xca, 0x56, 0x44, 0xbd, 0x59, 0x66,
	0x77, 0x27, 0x9b, 0xd1, 0xcd, 0xcc, 0x3a, 0x33, 0x1b, 0xba, 0xef, 0xe0, 0x73, 0x89, 0x4f, 0xe1,
	0x63, 0x78, 0x2d, 0x7b, 0xe6, 0x27, 0x41, 0xbc, 0x08, 0xcc, 0x7c, 0x3f, 0xcb, 0x39, 0x67, 0xbe,
	0x1c, 0x14, 0x54, 0xfc, 0x76, 0x52, 0xff, 0x96, 0xa7, 0x93, 0x8c, 0x72, 0xaa, 0x98, 0x1a, 0x17,
	0x52, 0x68, 0x81, 0x51, 0xc5, 0x6f, 0xc7, 0xf5, 0x6f, 0x79, 0x7a, 0xb8, 0x9f, 0x89, 0x4c, 0x00,
	0x3c, 0xa9, 0x4f, 0x46, 0x71, 0x78, 0x7f, 0xcd, 0x5b, 0x10, 0x49, 0x16, 0xd6, 0x7a, 0xfc, 0x67,
	0x13, 0x75, 0x6f, 0x2a, 0xa5, 0xe9, 0xe2, 0x52, 0xf0, 0x19, 0xcb, 0x70, 0x80, 0xb6, 0x28, 0x27,
	0x71, 0x4e, 0xd3, 0xa0, 0x31, 0x6c, 0x8c, 0xb6, 0x43, 0x77, 0xc5, 0x4f, 0xd0, 0x20, 0xa5, 0x45,
	0x2e, 0x2a, 0x2a, 0x23, 0x92, 0xa6, 0x92, 0x2a, 0x15, 0x6c, 0x0c, 0x1b, 0xa3, 0x76, 0xd8, 0x77,
	0xf8, 0xb9, 0x81, 0xf1, 0x19, 0x0a, 0x34, 0x25, 0x8b, 0x28, 0xa6, 0x9c, 0xce, 0x58, 0xc2, 0x88,
	0xac, 0xbc, 0xe5, 0x2e, 0x58, 0x0e, 0x6a, 0xfe, 0x62, 0x45, 0x3b, 0xe7, 0x6b, 0x74, 0x94, 0x88,
	0xc5, 0xa2, 0xe4, 0x4c, 0x57, 0x91, 0xa4, 0x09, 0x2b, 0x18, 0xe5, 0xda, 0x9b, 0x9b, 0x60, 0x7e,
	0xe0, 0x25, 0xa1, 0x53, 0x38, 0xff, 0x63, 0xb4, 0x63, 0x67, 0x13, 0xa9, 0xb2, 0x28, 0xf2, 0x2a,
	0xd8, 0x04, 0x4b, 0xcf, 0xa2, 0x37, 0x00, 0xe2, 0x47, 0xa8, 0x0b, 0x05, 0x16, 0x54, 0x26, 0x94,
	0xeb, 0xa0, 0x35, 0x6c, 0x8c, 0x7a, 0x61, 0xa7, 0xc6, 0xae, 0x0d, 0x54, 0xb7, 0xab, 0x25, 0x25,
	0xaa, 0x94, 0x95, 0x97, 0x6d, 0x81, 0xac, 0xef, 0x70, 0x27, 0x7d, 0x8a, 0x76, 0x57, 0x45, 0x3b,
	0xed, 0x36, 0x68, 0x07, 0x9e, 0x70, 0xe2, 0x31, 0xda, 0x5b, 0x0a, 0xcd, 0x78, 0x16, 0xa5, 0x34,
	0x27, 0x55, 0x14, 0xe7, 0x22, 0xf9, 0xa6, 0x82, 0xf6, 0xb0, 0x31, 0x6a, 0x86, 0xbb, 0x86, 0xba,
	0xaa, 0x99, 0x0b, 0x20, 0xf0, 0x09, 0xda, 0xb7, 0xfa, 0x82, 0x4a, 0x26, 0x52, 0x67, 0x40, 0x60,
	0xc0, 0x86, 0xbb, 0x06, 0xca, 0x3a, 0x9e, 0x23, 0x5c, 0x48, 0x51, 0x08, 0x45, 0xf2, 0x48, 0xcf,
	0x25, 0x55, 0x73, 0x91, 0xa7, 0x41, 0x07, 0xe6, 0xb0, 0xeb, 0x98, 0x0f, 0x8e, 0xa8, 0x1b, 0xf5,
	0xf2, 0x94, 0x16, 0x42, 0x31, 0x1d, 0x74, 0xcd, 0xbb, 0x3a, 0xfc, 0xca, 0xc0, 0xf5, 0x74, 0xbf,
	0x97, 0x42, 0x96, 0xab, 0xc1, 0xf5, 0xa0, 0x8a, 0x9e, 0x41, 0x5d, 0x8b, 0x2f, 0xd1, 0x81, 0x66,
	0x0b, 0x5a, 0x57, 0x63, 0x9b, 0x54, 0x34, 0x11, 0x3c, 0x55, 0xc1, 0x0e, 0xc8, 0xf7, 0x1d, 0x0b,
	0x7d, 0xde, 0x18, 0x0e, 0x4f, 0xd1, 0xbd, 0x25, 0x55, 0xd0, 0x69, 0x92, 0xb3, 0xd9, 0xcc, 0x9b,
	0xfa, 0x60, 0xda, 0xb3, 0xe4, 0x65, 0xcd, 0x39, 0xcf, 0x19, 0x0a, 0x9c, 0x27, 0x2d, 0x25, 0xd1,
	0x4c, 0x70, 0x6f, 0x1b, 0x80, 0xed, 0xc0, 0xf2, 0x57, 0x96, 0xb6, 0xce, 0xe3, 0x1f, 0x1b, 0xa8,
	0xef, 0x83, 0xaf, 0x25, 0x49, 0xb4, 0xc2, 0x18, 0x35, 0x79, 0x75, 0xab, 0x21, 0xf8, 0xed, 0x10,
	0xce, 0xf8, 0x10, 0x6d, 0xbb, 0x6a, 0x6d, 0xda, 0xfd, 0x1d, 0x38, 0x1b, 0x05, 0x1b, 0x6b, 0x7f,
	0xaf, 0xb9, 0x4c, 0x2c, 0xa9, 0xe4, 0x42, 0xda, 0xd4, 0xfa, 0xbb, 0x4f, 0x9f, 0x2d, 0xcd, 0x46,
	0x14, 0xd2, 0xf7, 0xd1, 0x40, 0xb5, 0x44, 0xc8, 0x2c, 0x92, 0x34, 0x63, 0x4a, 0xcb, 0x0a, 0x02,
	0xda, 0x0e, 0x3b, 0x42, 0x66, 0xa1, 0x85, 0xea, 0x77, 0x53, 0x65, 0xfc, 0x95, 0x26, 0x7a, 0x25,
	0xdb, 0x32, 0xef, 0x66, 0x71, 0x2f, 0x1d, 0xa2, 0x0e, 0x91, 0x31, 0xd3, 0x66, 0x04, 0x10, 0xcd,
	0x76, 0xb8, 0x0e, 0x1d, 0xff, 0x6c, 0xa0, 0xee, 0x1b, 0xfb, 0x17, 0xd1, 0x44, 0x53, 0x7c, 0x82,
	0x5a, 0x66, 0x51, 0xc0, 0x34, 0x3a, 0x53, 0x3c, 0x5e, 0x2d, 0x99, 0xf1, 0x35, 0x30, 0x17, 0xcd,
	0x5f, 0xbf, 0x1f, 0xde, 0x09, 0xad, 0x0e, 0xbf, 0x42, 0x2d, 0x05, 0x03, 0x85, 0x39, 0x75, 0xa6,
	0xc1, 0xba, 0x63, 0x7d, 0xc7, 0x38, 0x9f, 0x51, 0xe3, 0x77, 0x68, 0x60, 0x4e, 0x51, 0xe2, 0x5e,
	0x02, 0xa6, 0xd9, 0x99, 0x1e, 0xfd, 0xf7, 0x0b, 0x46, 0x62, 0x3f, 0xd2, 0x57, 0xff, 0xc0, 0xe3,
	0x2f, 0xcf, 0x32, 0xa6, 0xe7, 0x65, 0x3c, 0x4e, 0xc4, 0x62, 0xf2, 0x96, 0x91, 0x39, 0x11, 0xe7,
	0x79, 0x5c, 0xaa, 0xc9, 0xe7, 0xf7, 0x9f, 0x26, 0xc9, 0x9c, 0x30, 0x3e, 0x31, 0xab, 0x50, 0x57,
	0x05, 0x55, 0x71, 0x0b, 0xf6, 0xe0, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xd1, 0xeb,
	0x92, 0x5e, 0x05, 0x00, 0x00,
}
