// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ynx/ynx/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dcbb493bb41a18a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsRequest.Unmarshal(m, b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryParamsRequest.Size(m)
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params               Params   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dcbb493bb41a18a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsResponse.Unmarshal(m, b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryParamsResponse.Size(m)
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QuerySystemContractsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuerySystemContractsRequest) Reset()         { *m = QuerySystemContractsRequest{} }
func (m *QuerySystemContractsRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySystemContractsRequest) ProtoMessage()    {}
func (*QuerySystemContractsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dcbb493bb41a18a, []int{2}
}
func (m *QuerySystemContractsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySystemContractsRequest.Unmarshal(m, b)
}
func (m *QuerySystemContractsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySystemContractsRequest.Marshal(b, m, deterministic)
}
func (m *QuerySystemContractsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySystemContractsRequest.Merge(m, src)
}
func (m *QuerySystemContractsRequest) XXX_Size() int {
	return xxx_messageInfo_QuerySystemContractsRequest.Size(m)
}
func (m *QuerySystemContractsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySystemContractsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySystemContractsRequest proto.InternalMessageInfo

type QuerySystemContractsResponse struct {
	System               SystemConfig    `protobuf:"bytes,1,opt,name=system,proto3" json:"system"`
	SystemContracts      SystemContracts `protobuf:"bytes,2,opt,name=system_contracts,json=systemContracts,proto3" json:"system_contracts"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QuerySystemContractsResponse) Reset()         { *m = QuerySystemContractsResponse{} }
func (m *QuerySystemContractsResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySystemContractsResponse) ProtoMessage()    {}
func (*QuerySystemContractsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dcbb493bb41a18a, []int{3}
}
func (m *QuerySystemContractsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySystemContractsResponse.Unmarshal(m, b)
}
func (m *QuerySystemContractsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySystemContractsResponse.Marshal(b, m, deterministic)
}
func (m *QuerySystemContractsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySystemContractsResponse.Merge(m, src)
}
func (m *QuerySystemContractsResponse) XXX_Size() int {
	return xxx_messageInfo_QuerySystemContractsResponse.Size(m)
}
func (m *QuerySystemContractsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySystemContractsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySystemContractsResponse proto.InternalMessageInfo

func (m *QuerySystemContractsResponse) GetSystem() SystemConfig {
	if m != nil {
		return m.System
	}
	return SystemConfig{}
}

func (m *QuerySystemContractsResponse) GetSystemContracts() SystemContracts {
	if m != nil {
		return m.SystemContracts
	}
	return SystemContracts{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "ynx.ynx.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "ynx.ynx.v1.QueryParamsResponse")
	proto.RegisterType((*QuerySystemContractsRequest)(nil), "ynx.ynx.v1.QuerySystemContractsRequest")
	proto.RegisterType((*QuerySystemContractsResponse)(nil), "ynx.ynx.v1.QuerySystemContractsResponse")
}

func init() { proto.RegisterFile("ynx/ynx/v1/query.proto", fileDescriptor_5dcbb493bb41a18a) }

var fileDescriptor_5dcbb493bb41a18a = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xab, 0xcc, 0xab, 0xd0,
	0x07, 0xe1, 0x32, 0x43, 0xfd, 0xc2, 0xd2, 0xd4, 0xa2, 0x4a, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c,
	0x21, 0xae, 0xca, 0xbc, 0x0a, 0x3d, 0x10, 0x2e, 0x33, 0x94, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07,
	0x0b, 0xeb, 0x83, 0x58, 0x10, 0x15, 0x52, 0x12, 0x48, 0x3a, 0xd3, 0x53, 0xf3, 0x52, 0x8b, 0x33,
	0x8b, 0xa1, 0x32, 0xe2, 0x48, 0x32, 0x05, 0x89, 0x45, 0x89, 0xb9, 0x50, 0x09, 0x25, 0x11, 0x2e,
	0xa1, 0x40, 0x90, 0x1d, 0x01, 0x60, 0xc1, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x25, 0x77,
	0x2e, 0x61, 0x14, 0xd1, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x03, 0x2e, 0x36, 0x88, 0x66,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x21, 0x3d, 0x84, 0x93, 0xf4, 0x20, 0x6a, 0x9d, 0x58,
	0x4e, 0xdc, 0x93, 0x67, 0x08, 0x82, 0xaa, 0x53, 0x92, 0xe5, 0x92, 0x06, 0x1b, 0x14, 0x5c, 0x59,
	0x5c, 0x92, 0x9a, 0xeb, 0x9c, 0x9f, 0x57, 0x52, 0x94, 0x98, 0x5c, 0x02, 0xb7, 0x67, 0x09, 0x23,
	0x97, 0x0c, 0x76, 0x79, 0xa8, 0x8d, 0x66, 0x5c, 0x6c, 0xc5, 0x60, 0x29, 0xa8, 0x8d, 0x12, 0xc8,
	0x36, 0xc2, 0x35, 0xa5, 0x65, 0xa6, 0xc3, 0xec, 0x85, 0xa8, 0x16, 0xf2, 0xe1, 0x12, 0x80, 0xb0,
	0xe2, 0x93, 0x61, 0x66, 0x4a, 0x30, 0x81, 0x4d, 0x90, 0xc6, 0x6a, 0x02, 0x44, 0x09, 0xd4, 0x10,
	0xfe, 0x62, 0x54, 0x61, 0xa3, 0x1d, 0x8c, 0x5c, 0xac, 0x60, 0x67, 0x0a, 0x79, 0x72, 0xb1, 0x41,
	0xfc, 0x29, 0x24, 0x87, 0x6c, 0x0e, 0x66, 0x10, 0x4a, 0xc9, 0xe3, 0x94, 0x87, 0x7a, 0x2d, 0x85,
	0x8b, 0x1f, 0xcd, 0x7a, 0x21, 0x75, 0x0c, 0x3d, 0xd8, 0xc3, 0x4d, 0x4a, 0x83, 0xb0, 0x42, 0x88,
	0x2d, 0x4e, 0x7a, 0x51, 0x3a, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa,
	0x5e, 0x99, 0x89, 0x19, 0x89, 0xf9, 0x8e, 0x39, 0x49, 0xa5, 0xc5, 0xfa, 0x91, 0x7e, 0x11, 0xfa,
	0xc9, 0x19, 0x89, 0x99, 0x79, 0xfa, 0x90, 0x94, 0x51, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06,
	0x4e, 0x16, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0x97, 0x16, 0x5b, 0x85, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	SystemContracts(ctx context.Context, in *QuerySystemContractsRequest, opts ...grpc.CallOption) (*QuerySystemContractsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/ynx.ynx.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SystemContracts(ctx context.Context, in *QuerySystemContractsRequest, opts ...grpc.CallOption) (*QuerySystemContractsResponse, error) {
	out := new(QuerySystemContractsResponse)
	err := c.cc.Invoke(ctx, "/ynx.ynx.v1.Query/SystemContracts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	SystemContracts(context.Context, *QuerySystemContractsRequest) (*QuerySystemContractsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) SystemContracts(ctx context.Context, req *QuerySystemContractsRequest) (*QuerySystemContractsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemContracts not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ynx.ynx.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SystemContracts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySystemContractsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SystemContracts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ynx.ynx.v1.Query/SystemContracts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SystemContracts(ctx, req.(*QuerySystemContractsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ynx.ynx.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "SystemContracts",
			Handler:    _Query_SystemContracts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ynx/ynx/v1/query.proto",
}
