#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RPC_URL="${RPC_URL:-http://127.0.0.1:36657}"
INDEXER_URL="${INDEXER_URL:-http://127.0.0.1:38081}"
CHECK_INTERVAL_SEC="${CHECK_INTERVAL_SEC:-10}"
HEIGHT_STALL_THRESHOLD_SEC="${HEIGHT_STALL_THRESHOLD_SEC:-30}"
MIN_SIGNED_RATIO="${MIN_SIGNED_RATIO:-0.66}"
REQUIRE_BONDED="${REQUIRE_BONDED:-1}"
ALERT_COOLDOWN_SEC="${ALERT_COOLDOWN_SEC:-90}"

export RPC_URL
export INDEXER_URL
export CHECK_INTERVAL_SEC
export HEIGHT_STALL_THRESHOLD_SEC
export MIN_SIGNED_RATIO
export REQUIRE_BONDED
export ALERT_COOLDOWN_SEC

exec "$SCRIPT_DIR/testnet_watchdog.sh"
